# Generated by Django 4.1 on 2022-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('course_number', models.IntegerField()),
                ('teacher_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('department_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('semister_number', models.IntegerField()),
            ],
        ),
    ]
